//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wanna2
{
    using System;
    using System.Collections.Generic;
    
    public partial class wanna_probki_temperatury
    {
        public int id { get; set; }
        public int id_badania { get; set; }
        public System.DateTime data { get; set; }
        public decimal wartosc { get; set; }
    }
}
